name: gallery_app
description: A Flutter gallery app.

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.0
  photo_manager: ^3.7.1

flutter:
  uses-material-design: true
